import { useEffect, useState } from "react";
import { qrSvg } from "../api";

/** Shows a scannable QR code for a text/link item (e.g. to send a URL to a phone). */
export function QrModal(props: { text: string | null; onClose: () => void }) {
  const [svg, setSvg] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (props.text === null) {
      setSvg(null);
      setError(null);
      return;
    }
    let cancelled = false;
    qrSvg(props.text)
      .then((s) => !cancelled && setSvg(s))
      .catch((e) => !cancelled && setError(String(e)));
    return () => {
      cancelled = true;
    };
  }, [props.text]);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") props.onClose();
    };
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [props.onClose]);

  if (props.text === null) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-6"
      onClick={props.onClose}
    >
      <div
        className="flex max-w-sm flex-col items-center gap-3 rounded-xl border border-border bg-bg-raised p-5 shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        {error ? (
          <p className="text-sm text-red-400">Could not build QR code: {error}</p>
        ) : svg ? (
          <div
            className="h-56 w-56 [&>svg]:h-full [&>svg]:w-full rounded bg-white p-2"
            // The SVG is generated by our own backend (qrcode crate), not user HTML.
            dangerouslySetInnerHTML={{ __html: svg }}
          />
        ) : (
          <div className="h-56 w-56 animate-pulse rounded bg-bg-card" />
        )}
        <p className="max-w-full truncate text-xs text-fg-muted">{props.text}</p>
        <button
          onClick={props.onClose}
          className="rounded border border-border px-3 py-1 text-sm text-fg-muted hover:text-fg hover:border-accent"
        >
          Close
        </button>
      </div>
    </div>
  );
}
